### ISSUE TITLE
Voracious disk usage by storing function source code for inline calculations

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#1026]
Every inline calculation (and these are used quite often) stores both the source code of the function AND of the entire file. Besides redundancy here, this can also be using quite a bit of dis space, which can be said to be not worth the gain (after all, I've never had to query for the source code of an inline calculation).

Should we remove the storing of the file's source code?
And maybe also the function source code?
Or/and should we move the storage to the repository instead of the DB?

To be discussed, implementation is trivial.

**Comment by giovannipizzi** [comment]
I would keep at least the function source. Ok to remove the content of the whole file, anyway it does not help much to know what happens if the function calls another function in another file.
I agree this should not go in the DB but in the repository. This is an easy change.

IMPORTANT: the same should be done for workfunctions.

Hard task: decide if we want to migrate old inline calculations.

**Comment by ltalirz** [comment]
Just curious: would this problem simply go away when hashing is implemented?
I don't know the details, but it would seem like it should.

**Comment by giovannipizzi** [comment]
I'm not sure it would - currently the caching for calculations will anyway recreate a copy of the node to preserve acyclicity.

**Comment by lekah** [comment]
In case we want a migration, here a working (tested) SQL statement:
`delete from db_dbattribute where id in (select db_dbattribute.id from db_dbattribute join db_dbnode on db_dbnode.id = db_dbattribute.dbnode_id where db_dbattribute.key='source_file' and db_dbnode.type='calculation.inline.InlineCalculation.');`

But I would say this is not a worth a migration. I would just remove the storing of the source-file,  if everyone agrees, and leave old data untouched.

Now, should we move the saving of the code snippet (just function source!) to the repository? Is that what everyone wants?

**Comment by giovannipizzi** [comment]
If the idea is just to remove the source, I think it's ok not to put a migration. It's ok to use the SQL statement (for those who know what they are doing), as a note during sharing the 'old' version of the inline calculations will be kept (with the source code) if they were already shared.

**Comment by broeder-j** [comment]
One comment to the function source code: I personally write always a function which is not an wf/inline calculation and then a second one which wraps the original function. Therefore (also in general) you do not see the full source code of the inline calculation in the database anyway (because imported methods could have changed). But this reduces space and allows me to write new wf which use several of these nonwf instead of using 10 wf in a row. Storing the file is not really better if methods are imported from the outside.

**Comment by broeder-j** [comment]
But if only stored in a file in the repo, and maybe a hash of it in the database, this should reduce the space needed, because then caching will solve it.
