### ISSUE TITLE
verdi -p [sqla profile] calculation list produces user error

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1156]
`
(aiida_core)  martin@picolino  ~  verdi -p test_sqla calculation list 
# Last daemon state_updater check: (Never)
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/aiida_core/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/martin/src/aiida_core/aiida/cmdline/verdilib.py", line 1052, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/martin/src/aiida_core/aiida/cmdline/verdilib.py", line 1037, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/martin/src/aiida_core/aiida/cmdline/baseclass.py", line 217, in run
    function_to_call(*args[1:])
  File "/home/martin/src/aiida_core/aiida/cmdline/commands/calculation.py", line 219, in calculation_list
    projections=parsed_args.project,
  File "/home/martin/src/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1001, in _list_calculations
    user_id = get_automatic_user().id
  File "/home/martin/src/aiida_core/aiida/backends/utils.py", line 89, in get_automatic_user
    return get_automatic_user_sqla()
  File "/home/martin/src/aiida_core/aiida/backends/sqlalchemy/utils.py", line 121, in get_automatic_user
    email))
aiida.common.exceptions.ConfigurationError: No aiida user with email aiida@localhost
`

**Comment by szoupanos** [comment]
I used the branch release_v0.11.1 and  I am unable to reproduce it on 5 out of 6 sqla databases that I have. One of the sqla databases was old enough (before introducing alembic migrations) that I had to follow what was described at http://aiida-core.readthedocs.io/en/latest/developer_guide/developers.html#first-alembic-migration
Migrations worked for that database and I managed to do a calculation list.

The only database that gave me the message that you mention, had an empty db_user table (very likely because I emptied the database manually). So the message was normal.

Overall, I see that in the tearDownClass_method  of SQLA (aiida.backends.sqlalchemy.tests.testbase.SqlAlchemyTests#tearDownClass_method) we empty the database (at the end of every test class). I mention this because I see that the profile that you had in your error message seems to be a test profile. So it is "normal" to have an empty db_user table for this database at the end of the tests.

Moreover, such profiles, are not expected to be left at a working state to be usable with verdi commands afterwards. We can do it but I don't know if we should invest time on this. Of course at the beginning of every test there are methods that properly populate an empty database.

Let's have a closer look at your machine on what is going on and at the corresponding database.

**Comment by sphuber** [comment]
Did you create the profile through the verdi setup? I.e. `verdi setup test_sqla`? Because that should have created the database and then the default user. Or if you created it with a different user email at first and then changed the configuration file, the user might also not exist.

**Comment by muhrin** [comment]
Closing as not reproducible.
