### ISSUE TITLE
Add logic for "internal" extras

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1158]
Currently, the "internal" extras ``_aiida_hash`` and ``_aiida_cached_from`` are treated exactly like regular extras. However, in some places this might not be appropriate:

- In ``reset_extras``, they should not be cleared by default, but only if a specific flag is set
- The tests should be written in such a way that they don't fail if a new internal extra is added
- It should be documented that AiiDA can add additional internal extras when needed, so that the user doesn't depend on the extras being _only_ what was specified with ``set_extra``.

We decided that we _do_ want to see internal extras in ``get_extras``. 

Extras should be considered internal if they start with ``_aiida_``.

**Comment by sphuber** [comment]
Just for reference, in PR #1181 the `hidden` attribute of the `Code` class was migrated to be an extra. When this issue is addressed, we may also want to include that `hidden` extra. Currently it is literally also labeled `hidden` which might be undesirable for when users may want to use that extra key

**Comment by greschd** [comment]
Following this new convention about "internal" extras, that extra should then be called either ``_aiida_core_hidden`` or ``_aiida_hidden`` (we haven't decided which one to use yet).

**Comment by giovannipizzi** [comment]
Sorry, I reopened this... Closing this in favour of #2231
