### ISSUE TITLE
'verdi devel run_daemon' gets stuck after running for a long time

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1275]
After running 'verdi devel run_daemon' for a long time (~ a few hours), it gets stuck, idling at 100% CPU usage. It seems as if there is some loop which doesn't release the event loop.

Workload: Running a workchain which submitted long-running calculations to a remote computer (ssh / slurm).

May be related to #1274.

**Comment by greschd** [comment]
strace for a daemon which appears to be stuck (actually, after less than an hour). There appears to be a repeating pattern at the end.

[strace.txt](https://github.com/aiidateam/aiida_core/files/1806609/strace.txt)

**Comment by greschd** [comment]
@sphuber Does issue #1235 affect also daemons started with `devel run_daemon`, or only those started through `daemon start`? The reason I'm asking is because I've now successfully ran the long calculation which previously failed. One thing which I hadn't properly checked before was whether there might be a rogue daemon process still running (from a temporary profile, for example). So in the end that could just be a manifestation of #1235.

Another thing which I could imagine giving rise to this sort of error is if the connection to the computer is lost, and somehow not properly re-established.

**Comment by sphuber** [comment]
I don't think if you run `verdi devel run_daemon` straight up should be affected by that, because it does not involve a circus daemon, which is the one that requires the port. However, running two daemons for the same profile might be problematic. This is checked when going through the `verdi daemon` commands. However, I think that you can still just run `verdi devel run_daemon` in parallel, so then there will be two instances running like that for one profile. That might be problematic. I will open a PR for #1235 in a minute. I think that should fix that. Could you perhaps check that out, make sure that you kill all aiida related processes first and then run a fresh daemon and see if then still you can reproduce the problem? Thanks

**Comment by greschd** [comment]
Well, I'm already having trouble consistently reproducing the error now, it's not getting easier once you start fixing stuff :smile:

**Comment by sphuber** [comment]
Not so sure if we can call it "fixing" yet  :smile:

**Comment by greschd** [comment]
Another maybe-related behaviour is that the daemon sometimes ignores Ctrl-C (even after letting it run for a while) and needs to be killed. That would be consistent with being stuck inside a function that doesn't release the event loop.

**Comment by greschd** [comment]
Wouldn't it make sense to change the default log level for the daemon to at least ``INFO`` (currently ``REPORT``)? I just realized that I would probably have some more info about what went wrong if I'd set the log level differently.

**Comment by greschd** [comment]
Closing this because I could never reproduce it after the initial error.
