### ISSUE TITLE
Give the possibility to copy remotely using hardlinks instead of a real copy

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#128]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

The real copy is extremely slow when the scratch files are ~100GB.
Moreover, this solves the scratch size issues that AiiDA might generate with multiple restarts.

From 'man cp'

      -l, --link
             hard link files instead of copying

One should probably check if hardlinks are supported, and fall back to a standard copy otherwise (to add to 'computer test'?)

We should also test if it works properly with the recursive -r option.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/128

**Comment by DropD** [comment]
Hard link is preferrable because as long as a hard link exists, the underlying inode will be kept even if the original file (which conceptually is a hard link to the same inode) is deleted (by the scratch system).

**Comment by DropD** [comment]
Actually, using `ln` would be preferrable because it standardly creates hard links on every UNIX system, whereas `cp -l` is not available everywhere.

**Comment by DropD** [comment]
At the moment, every calculation plugin needs to implement it's own restart machinery in `_prepare_for_submission`. However, the calcinfo object provides a way to specify symlinks to a parent calculation's work directory. Maybe in addition to or instead of that a hard link functionality could be added.

@giovannipizzi, @yakutovicha : I do not quite understand the machinery involved here. Is this still relevant or will the problems involved be vanish as the whole storage effort progresses?

**Comment by DropD** [comment]
Closing for the following reasons:
* It is unclear whether QE copies hard links before modifying
* There have been no issues with originals being deleted by scratch

Therefore there is no known use case for hard links.
