### ISSUE TITLE
Calculation kill

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#133]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

Calculations should be killed by the daemon to avoid concurrence problems (same for workflows).

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/133

**Comment by lekah** [comment]
I don't quite understand. What concurrence problem are we talking about? 
@giovannipizzi , @nmounet

**Comment by giovannipizzi** [comment]
Currently, ``verdi calculation kill`` when called tries to connect directly to the computer via ssh, and runs the ``scancel`` or equivalent commands to kill the job, and will then set a message in the calculation log (visible with logshow). 

However, in the meantime the daemon in parallel could be performing other operations that are not necessarily compatible. E.g., (especially if you provide a long list of calculations to kill, so it takes time to do it for all of them) you call kill when the calculation was still running, but in the meantime it finishes and you call the command while files are being retrieved. 

Or, even worse, when you start the ``kill`` command the calculation is still TOSUBMIT, so AiiDA does not run ``scancel`` via ssh, but just changes the state to FAILED (to prevent submission). But in the meantime the daemon submits the calculation. Then, what happens is that the calculation gets submitted by the daemon and will run, but AiiDA - by the verdi process - a few seconds after sets the state to FAILED (because it killed it) and does not check it anymore, nor will it retrieve its output. Also, it is very hard for the user to realise that he's spending CPU hours, and which calculation should he manually kill.

**Comment by waychal** [comment]
This issue is not fixed yet so will keep it open.

**Comment by muhrin** [comment]
Fixed by #1321 .  Now requests to kill will be pooled and sent over one SSH connection.
