### ISSUE TITLE
Check on parsing state in parsers in the wrong place

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#141]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

The CP parser (and I guess many others) has this code inside it (now commented out):
```
#!python
state = self._calc.get_state()
if state != calc_states.PARSING:
    raise InvalidOperation("Calculation not in {} state"
                           .format(calc_states.PARSING) )
```
We don't want that this check is done by each plugin. Move this to the main class removing it from all plugins, and think to a way to skip this test if for some reason reparsing is necessary.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/141

**Comment by giovannipizzi** [comment]
Decide and document what's the suggested way to write parsers

**Comment by DropD** [comment]
## Current state
Current policy is that this check is not required. It is safe to call the parser anyway because it does not store nodes, that is the daemon's responsibility. The parser can be easily tested this way and the daemon will only call the parser on a calculation in parsing state anyway.

## To do
* remove the check from documentation examples
* create issues to qe-plugin repo where this check is still done.
