### ISSUE TITLE
Calculation not going in SUMBISSIONFAILED

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1523]
if ssh connection fails (e.g. no key in the ssh-agent or any other similar reason, like no network, I imagine) I get this state for calculations:
```
224347  2m ago      Excepted | None  quantumespresso.pw  daint-mc    TOSUBMIT | None
```
Moreover, due to #1522, I can't remove it from the list of past calculations.
Shouldn't this go to submission failed? Or maybe there is a way to recover it?

**Comment by sphuber** [comment]
As far as the process is concerned, this is a consistent state. The process is terminated (it is in the terminal `excepted` state) because during process execution an exception was thrown that was not caught. My feeling is that the submission code of the execmanager does not correctly catch the exception that was thrown in your example. If it does and catches it, it can set the calculation state to `SUBMISSIONFAILED` and set the corresponding finish status. The process will then wrap up, set it to `Finished` and combined with the non-zero `finish_status` it will be considered as `Failed`.

**Comment by sphuber** [comment]
Exception in transport tasks of JobProcesses are now dealt with gracefully by the exponential backoff retry and pause mechanism, which is merged into `develop`.
