### ISSUE TITLE
Calculation failed - command not found

### ISSUE THREAD

**Issue by kimbold** [aiidateam/aiida_core#1598]
I am following along [this tutorial](http://aiida-core.readthedocs.io/en/latest/developer_guide/devel_tutorial/code_plugin_int_sum.html) for the Calculation plugin and when I submit my calculation it fails:

```
*** 28 [Test sum]: FAILED
*** (empty scheduler output file)
*** Scheduler errors:
./sum_executable.py: line 4: in_file: command not found
./sum_executable.py: line 5: out_file: command not found
Warning: unknown mime-type for "Some output from the code" -- using "application/octet-stream"
Error: no such file "Some output from the code"
./sum_executable.py: line 9: syntax error near unexpected token `('
./sum_executable.py: line 9: `with open(in_file) as f:'

*** 2 LOG MESSAGES:
+-> ERROR at 2018-05-25 09:10:15.683898+00:00
|   Output json not found
+-> ERROR at 2018-05-25 09:10:15.697410+00:00
|   [parsing of calc 28] The parser returned an error, but it should have created an output node with some partial results and warnings. Check there for more information on the problem
```

My sum_executable.py is the one I downloaded from the tutorial link and looks therefore like this:

```
import json
import sys

in_file = sys.argv[1]
out_file = sys.argv[2]

print "Some output from the code"

with open(in_file) as f:
    in_dict = json.load(f)

out_dict = { 'sum':in_dict['x1']+in_dict['x2'] }

with open(out_file,'w') as f:
    json.dump(out_dict,f)

```

I don't understand why these errors occur, especially the one with `Error: no such file "Some output from the code"` since it's just the print line. 
It also says that the parser returned an error and that I can check there for more information. How do I do that? Is there a logfile for the returned error from the parser? 

As a note - in the tutorial it says that the output plugin should be placed at `aiida/parsers/plugins/sum.py` but I noticed that there is no subfolder in "parsers" called "plugins" so I created one and placed it there. Is that the correct location for the parser? And a folder called "plugins" exist though but as aiida/plugins. 

I am using the version 0.12.0. 

Thanks for helping

**Comment by giovannipizzi** [comment]
You need to add, I think,
```
#!/usr/bin/env python
```
as the first line of your file, otherwise the command runs as a bash script. Could you check and tell if this solves the issue (and in this case close this issue, sand if needed do a Pull Request to fix the docs if this should be mentioned there?

Also, for the parser, I think the folder is simply `aiida/parsers`, would you be able to make a PR to fix this? Also, I mention here (I have to check if this already documented, probably the docs need to be updated) that the suggested way is more to put parsers in independent packages and use entry points: http://aiida-core.readthedocs.io/en/latest/developer_guide/plugins/entry_points.html#aiida-parsers

**Comment by kimbold** [comment]
Thanks for your answer! Yes that fixed it. I don't know why I didn't have it in my file because when I checked it, it was in the file attached to the wiki.
