### ISSUE TITLE
Daemon workers do not automatically recreate lost connection

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1822]
Due to the limited heartbeat timeout that is set by the default configuration of the RabbitMQ server (see #1821), the connection of daemon workers are often closed by the server. Currently, the worker does not seem to be able to automatically reopen its connection

**Comment by muhrin** [comment]
Again as with #1821 this should be fixed by `plumpy` v0.11.  This one is perhaps even more tricky to test as it requires externally forcing a connection drop and checking if the connection comes back.  I think we should really push this back to `kiwipy` as it is responsible for making sure that the communicator reconnects itself.  If this works, `plumpy` and aiida _should_ also.
