### ISSUE TITLE
Help string of click.Choice in interactive mode broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1950]
For example in `verdi computer configure ssh`, calling `?` for the `key_policy` question results in:
```
Info: SSH key policy
one of:
	R            e
	W            a
	A            u
```
These should however be
```
Info: SSH key policy
one of:
    RejectPolicy
    WarningPolicy
    AutoAddPolicy
```

**Comment by dev-zero** [comment]
Looked into this shortly since I'm currently monitoring issues for possible regressions from my py3-compat merge. The problem is here:
https://github.com/aiidateam/aiida_core/blob/a94294fc3f72e1a55b0c39b74ffad04050a6d186/aiida/cmdline/params/options/interactive.py#L136
The code expects `choices = [("ab", "bc"), ("cd", "de")]`, while it gets `choices = ["ab", "bc"]` instead, but all our implementions of `def complete` seem ok, as does the base implemention in `click-completions` (which got a new release ,btw).

**Comment by sphuber** [comment]
It seems that `click-completion` overrides the `complete` method of the `click.Choice` class with the following:
```
def choice_complete(self, ctx, incomplete):
    return [c for c in self.choices if c.startswith(incomplete)]
```
which is not the list of tuples format that the `format_help_message` of our interactive option expects.
As far as I can tell, `click` does not define the concept of the parameter `complete` method and this is just implemented by `click-completion`. The latter seems to define a flat list as the return type of that method and it is us who changed that to be a list of tuples, where the first element is the value and second is a description. In our current implementations we never actually use the description element and always set an empty string. Should we just get rid of the description and therewith the tuple format and just resort to flat list? Or should we agree that we maintain the tuple format and override the `complete` methods that `click-completion` defines

**Comment by sphuber** [comment]
@dropd what was your original thinking to decide to have the choice complete return tuples of (`name`, `description`) instead of a flat list? Do you think we should change all our implementations to just flat lists, or simply override the complete of `click.Choice` implementation by `click-completion` with our own?
