### ISSUE TITLE
Requirement of wallclock

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1985]
There is now a requirement of supplying `max_wallclock_seconds`. This might make sense for some cluster, others not. Also, it now also wants this for typical local runs (e.g. for tests). Maybe we at least can remove this requirement for the local scheduler?

**Comment by greschd** [comment]
I strongly support this, since it's a backwards-incompatible change without real need. We could just have a default (no limit) on the ``max_wallclock_seconds``. @giovannipizzi, @sphuber, opinions?

**Comment by greschd** [comment]
In https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/implementation/general/calculation/job/__init__.py#L358, there is actually a default defined, so I'm wondering if this might just be a bug.

**Comment by sphuber** [comment]
This is due to a [recent change](https://github.com/aiidateam/aiida_core/pull/1961/files#diff-bfa9b3df14d2db1db32f188e610ce678R629) I made. I thought the `max_wallclock_seconds` used to be required before this change, so I left it required. The default does not make a lot of sense then. If this attribute was not required before this change, I agree we should revert this change and make it optional again without a default.

**Comment by greschd** [comment]
I'm not sure if there was a default before, but it definitely wasn't required to manually pass it.

**Comment by sphuber** [comment]
Yeah, I just verified manually in a legacy environment running `0.12.*` that this was not required. I will put in the fix

**Comment by espenfl** [comment]
Great. Thanks.
