### ISSUE TITLE
Django dependency needs to be update to 1.11.x

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#2010]
Django 1.8.19 is already EOL and needs to be updated to the 1.11.x LTS-branch which provides Python 2.7 support until 2020. Unfortunately, upstream decided to remove `django.utils.unittest` (used in `aiida/tools/dbimporters/plugins/test_icsd.py`) plus some more changes which may require yet another migration of the DB schema.

**Comment by sphuber** [comment]
@szoupanos should already be looking into this. Have you already had a chance to take a look to get an estimate of how much work it would be to update to `1.11.*`?

**Comment by szoupanos** [comment]
I am performing some experiments to test the performance of the latest version of Django that supports Python 2.7. One of the next goals is to have an understanding about the changes that we need to perform to AiiDA to support JSON fields (using Django). I can also have a look at the needed changes to support 1.11.x (e.g.1.11.15) since I also observed what is mentioned by @dev-zero

**Comment by sphuber** [comment]
Fixed in PR #2206
