### ISSUE TITLE
a/o/i/g/node.py: clean_value silently converts numpy.array in node attribute to nested list

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#2038]
The following code transparently and silently converts a `numpy.array` as (or inside) a node attribute to a nested list:

https://github.com/aiidateam/aiida_core/blob/ebf16441a3910d5b783100c13ddf3b5f6fcc6b1f/aiida/orm/implementation/general/node.py#L62-L67

Is that intentional behavior? The documentation only speaks of `BaseType AiiDA data nodes and List`, nothing was mentioned about other values.

As a plugin writer I would rather prefer a clean assert instead of silent conversion.

also, why is that only done explicitly for a `dict` and not generally for `dict.Mapping`?:

https://github.com/aiidateam/aiida_core/blob/ebf16441a3910d5b783100c13ddf3b5f6fcc6b1f/aiida/orm/implementation/general/node.py#L59

**Comment by giovannipizzi** [comment]
The aim of clean_value is exactly to bring the data format to something that is then (hopefully) idempotent after serializing/deserializing to the DB.

If we want, we can add an option to store to stop instead of running clean_value.
Also, there is a way *not* to run clean_value at every `set_attr` (for efficiency reasons, if you are sure you are passing "clean" data.

I agree that it should be dict.Mapping

Tasks:
- [ ] Document what `clean_value` does and explain when it is done
- [ ] Document the `clean` flat of `set_attr`
- [ ] fix this line to use `dict.Mapping` instead of only `dict` https://github.com/aiidateam/aiida_core/blob/ebf16441a3910d5b783100c13ddf3b5f6fcc6b1f/aiida/orm/implementation/general/node.py#L59

**Comment by ConradJohnston** [comment]
@giovannipizzi , should we also provide the option to disable cleaning when setting/resetting extras?

**Comment by giovannipizzi** [comment]
In general I would say that everything that is done for attributes should be done for extras.
However, attributes are cached and stored only upon `.store()` (and IIRC anyway at `.store()` a `clean_value` is run, right?), while for extras they are set instantaneously so probably it does not make much sense to provide a clean=False operation there? We just have to make sure there is a 'bulk set' operation that cleans only once if needed (this should be set_extras).

Could you confirm that a final cleaning is done in any case before storing? And that set_extras does a single cleaning of everything?

**Comment by ConradJohnston** [comment]
When set_extras is called is called, yes, each value in the dictionary is cleaned by a call to clean_values.
For the attributes, it is similar. When store() is called, eventually, set_attr() is called which calls the check for each value.

**Comment by sphuber** [comment]
Fixed in PR #2295
