### ISSUE TITLE
CLI of `verdi export create` can be a bit confusing

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#2076]
There are a couple of issues in the command-line interface of `verdi export create`:
* Options that can take multiple arguments (such as `--nodes`) do not specify what the separator between arguments should be. By trial and error, I found it to be a space: are other separators also accepted?
* Because the space is a separator for the above, the following command would not work:
`verdi export create --nodes 1 outfile.aiida`, because `outfile.aiida` is interpreted as a further argument for `--nodes`. However, this is the format that the usage string currently suggests: `Usage: verdi export create [OPTIONS] OUTPUT_FILE`

I see a few possibilities (not mutually exclusive) to fix this, but I'm not sure if they are all feasible:
* change the separator for multiple-argument options to a comma;
* change output_file from a basic (positional) argument to a named option (e.g. `-o, --output`);
* amend the usage string to have `OUTPUT_FILE` at the beginning, and explicitly state what the separator is for multiple-argument options.

**Comment by sphuber** [comment]
This is a known "problem" and is not exclusive to `verdi` but to any CLI. When one supports "multiple value options" it becomes impossible for the parser to know, if there is an optional positional argument in the spec, when the values are done and it should stop interpreting it as option values. The canonically accepted way of delimiting the two is through the `ENDOPTS` marker which is `--`. All of this I have [documented in a detailed manner](https://aiida-core.readthedocs.io/en/latest/verdi/verdi_user_guide.html#multi-value-options). I think the only thing we should maybe change is to make this more easily findable as I do not think we should change the behavior of the CLI because `verdi export create` is not the only end point with these characteristics.

**Comment by borellim** [comment]
Thanks a lot for the explanation!

I'm not sure I agree with the choice of space as a separator for multi-value options. For instance, I find the following command from SLURM more intuitive: ` squeue -u user1,user2,user3`. However, I see the point in not changing something that is already established and uniform across the verdi CLI. In which case, yes, I agree that the `--help` message should be more explicit, both with regards to the `--` marker and to what is the separator for multi-value options.

**Comment by sphuber** [comment]
The thing is that with the migration to `click` these concepts are now general to all `verdi` commands. To me it does not make much sense to start adding these general help concepts manually in all commands. Since they are generally applicable, I explained them in one place in great detail. This way I also have the space to explain why this is the case. As long as we can make this piece of information easily findable for users, it should be fine. I guess we should start making a FAQ page, that we can make highly visible. These pages can then point to the various point in the docs

**Comment by borellim** [comment]
Could you at least add a `[--]` between `[OPTIONS]` and `OUTPUT_FILE` in the usage string? Is this possible with click?

(See for example `man git reset`: `git reset (--patch | -p) [<tree-ish>] [--] [<paths>...]`).

**Comment by sphuber** [comment]
That would be a good suggestion yes, although it may not be trivial to implement. The help string is auto-generated by `click`. Luckily `click` is well-designed so we might be able to add custom rules in the formatting of the help string. Essentially what we should do is detect for a given command, if it has one ore more options of class `MultiValueOption` and one or more positional arguments. In that case, the `[--]` string should be inserted in between the `[OPTIONS]` and `ARGUMENT` strings.

**Comment by borellim** [comment]
> if it has one ore more options of class MultiValueOption

... or maybe even any non-boolean and non-positional option, if it's easier.

**Comment by sphuber** [comment]
I think the ambiguity only ever arises with a MultiValueOption present, so that should be the only case when `--` would ever be needed
