### ISSUE TITLE
Calculation gets stuck in TOSUBMIT state when submit_test was done just before

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida_core#2229]
I am working with the current develop version.
After I set up a new calculation I first looked at the output of
```
calc.submit_test()
```
which was then followed in my jupyter-notebook by
```
calc.store_all()
calc.submit()
```

Then the daemon does not process this calculation properly, i.e. it get's stuck in the TOSUBMIT state. I verified that the daemon and rabbitmq are running.
```
$ verdi calculation list -a -p1
verdi  PK  Creation    State            Type             Computer    Job state
----  ----------  ---------------  ---------------  ----------  ---------------
  46  2m ago      Excepted | None  kkr.voro         iff003      TOSUBMIT | None
```

I guess the log file of daemon contains a hint why this does not work:
```
11/22/2018 10:50:45 AM <7889> aiida.orm.implementation.django.calculation.job.JobCalculation: [REPORT] [46|ContinueJobCalculation|on_except]: Traceback (most recent call last):
  File ".../aiida/virtenv_aiida_1.0/lib/python2.7/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File ".../aiida/aiida_core/aiida/work/job_processes.py", line 686, in run
    return super(ContinueJobCalculation, self).run()
  File ".../aiida/aiida_core/aiida/work/job_processes.py", line 632, in run
    calc_info, script_filename = self.calc._presubmit(folder, use_unstored_links=False)
  File ".../aiida/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1791, in _presubmit
    calcinfo = self._prepare_for_submission(folder, inputdict)
  File ".../aiida/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1645, in _prepare_for_submission
    raise NotImplementedError
NotImplementedError
```

However, if I omit the `submit_test` step and directly go to `calc.submit` the calculation starts properly.
```
$ verdi calculation list -a -p1
  PK  Creation    State            Type             Computer    Job state
----  ----------  ---------------  ---------------  ----------  ---------------
  46  2m ago      Excepted | None  kkr.voro         iff003      TOSUBMIT | None
  47  50s ago     Finished | 0     kkr.voro         iff003      FINISHED | DONE
```

**Comment by sphuber** [comment]
Thanks for the report @PhilippRue . It seems like when you call `submit` on the `calc` instance, it loses the actual calculation class and falls back on the base class `aiida.orm.implementation.django.calculation.job.JobCalculation`. This base class does not implement the `_prepare_for_submission` method, as that is the job of the actual plugin class to implement. I will have to look why the actual class is lost, but this is probably because we have to pipe this old way of submitting jobs though the new process layer.

As a side note, the method you use here of submitting a calculation, i.e. calling `CalculationClass.new_calc` followed by calling the `use_` methods, is deprecated and will be removed in the future. Instead, one should simply submit/run the calculation class or use the process builder. This is explained [in the documentation](https://aiida-core.readthedocs.io/en/latest/concepts/processes.html?highlight=process%20builder). I can heartily recommend you start using this method of submission which should not have this issue.

**Comment by sphuber** [comment]
Closing this as this old way of submitting has been removed in `1.0.0b1`
