### ISSUE TITLE
Document backwards-incompatible things in 1.0.0

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2320]
Merge things with this:
https://aiida-core.readthedocs.io/en/latest/concepts/workflows.html#upgrading-workchains-from-pre-v1-0-0
and move to Install->Updating installations.

**Please dump all changes in [this wiki page](https://github.com/aiidateam/aiida_core/wiki/Backward-incompatible-changes-in-1.0.0).**

**Comment by sphuber** [comment]
Fixed in PR #2483

**Comment by giovannipizzi** [comment]
#2482 is about moving from wiki to sphinx, that I would do in 1.0.0
I reopen this as the wiki content has not been cleaned up before the beta yet.

**Comment by sphuber** [comment]
I have cleaned up the list @giovannipizzi and I made today from @ConradJohnston 's original list and [put it on the wiki](https://github.com/aiidateam/aiida_core/wiki/Backward-incompatible-changes-in-1.0.0). Since the main job is now done, and we will have to continuously update it while we find new incompatibilities, can this issue be closed?

**Comment by giovannipizzi** [comment]
I think so. I'll close it. @ConradJohnston maybe if you have time you can double check the text and clarify if needed? thanks!
