### ISSUE TITLE
Automatic creation of the aiida directory fails if AIIDA_PATH is set

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#2337]
When setting `AIIDA_PATH` in the environment, the `.aiida` folder is not created automatically and it defaults to the home directory `.aiida` (which is does create automatically). Creating it manually works. Could we consider to change this behavior?

**Comment by giovannipizzi** [comment]
Hi, I think the original implementation by @greschd allowed to define it, and was looking also into the parent folders up to the filesystem boundary. If no .aiida was found, the default one was used.
The main reason is that you could have set AIIDA_PATH='.' and have a 'git-like' behaviour, i.e. while being in a given folder you would use the .aiida folder where you were in (or the closest parent folder).

I agree that, after using this a bit, I also agree with @espenfl user expectation (and I'm not really using '.' as an AIIDA_PATH. Maybe we could just leave an exception when the path is set to the string `.` to check in the parent folders, but in all other cases we assume that the AIIDA_PATH is the *exact* folder where .aiida is expected to be found? @sphuber what do you think?

**Comment by sphuber** [comment]
Actually, if I understand the code correctly, using `AIIDA_PATH='.'` won't even work as you describe it, because the unwrapping of the path does not consider the current working directory. It will just take the components of the path and move up the directory tree until it finds an `.aiida` directory.

I personally do not use this functionality, as I always set the exact path, but if we were to demand that the exact path be defined, then the current implementation will not work as you describe when just passing `.`. If we were to implement that though, what starting directory would `.` signify? The directory of the `verdi` binary? Of the `aiida` package?

**Comment by zhubonan** [comment]
I had this issue initially as well and it took me a few attempts to realize that .aidda folder is not created  automatically and the default .aiida folder is still used. If we always expect an exact path then perhaps a warning message can be printed if the variable is defined but no valid folder can be found?

**Comment by greschd** [comment]
Previous discussion: https://github.com/aiidateam/aiida_core/pull/616

@sphuber The ``os.path.abspath`` in the ``find_path`` function expands ``'.'`` to the CWD, so it should work in the git-like way that @giovannipizzi described.

The issue here comes from the fact that we always keep ``~/.aiida`` as a fallback option, even when an explicit ``AIIDA_PATH`` is set. So this happens also when an explicit path is set, as long as there is a ``~/.aiida`` but no ``$AIIDA_PATH/.aiida``.

I seem to remember we were aware of this limitation when discussing the feature -- maybe it just needs better documentation that the ``.aiida`` folder needs to be created manually in this case?

Another solution would be to only use the ``~/.aiida`` fallback if _no_ ``AIIDA_PATH`` is set. That would create potential problems with ``AIIDA_PATH='.'`` with accidental folder creation though -- but that could still be averted by explicitly setting it to ``AIIDA_PATH='.:~'``.

**Comment by espenfl** [comment]
I think manually creating the `.aiida` folder makes little sense, given that you have `verdi setup` running etc. already. In my mind, if you set `AIIDA_PATH`, the program should check if it exists. If it does not, pull the plug and return with some kind of meaningful message. But then we might just create it. If we set `AIIDA_PATH='.'` We already create the `.aiida` in the user directory if it does not exist, so it should be the same. I would also assume we do the same operations in CWD. Have not checked the internals, but the CWD might change it it expands when we run `verdi setup` etc. But the user should know this when specifying `'.'`. At the very least we should document that `.aiida` need to be created if you want the repo under `AIIDA_PATH` and give the user a message during `verdi setup` that something default was used.

**Comment by greschd** [comment]
Yeah, the problem is that with the fallback to ``~``, and upwards path traversal, it most probably _does_ find a ``.aiida`` folder. But of course it's not the one you wanted.

If it doesn't find the ``.aiida`` folder at all it's still created, but in that case it will always be the fallback ``~/.aiida``. So to solve this one could simply ditch the upwards path traversal and fallback to ``~``.

Personally I use ``AIIDA_PATH='.'`` and upwards path traversal in development to easily switch between different test configs, but of course if I'm the only one to ever use it it's not worth keeping around. It's a bit hard to estimate if people are actually using this, though.

If we want to make ``'.'`` and automatic folder creation work there would need to be some way to enable upwards path traversal explicitly -- ``'.'`` without path traversal makes little sense. I'm not a great fan of having an exception specifically for ``.``, but maybe prepending the path with something like ``?`` would be ok? But again, that might not be worth the complexity if the user base is an almost-empty set.

**Comment by greschd** [comment]
On the issue of CWD changing, I think that works because the ``AIIDA_PATH`` is expanded / fixed to ``AIIDA_CONFIG_FOLDER`` when the configuration is first loaded. So it doesn't matter if the CWD changes after that point.

**Comment by espenfl** [comment]
I use the `AIIDA_PATH` and would like everything to be contained in there due to multiple branches of both plugins and core. Every time I have had to install it for regular users I have found it a little bit annoying that the directory has to be set explicitly. And most people react with: "why do I have to do that?" In general, in fact I prefer data that belongs to virtual environments to also be contained in them by default. Also, when you have a dormant `~/.aiida` from e.g. a previous profile or install it would default to that. Which might also not be what the regular user want.

So in general I think we should look at this from the regular user perspective, not the developers. In this case I think when you set `AIIDA_PATH` the user expect the same behavior as when this is not set, e.g. the creation of an `~/.aiida` folder in there.

But I have no real strong feelings, except that we should at least document it and possibly give a message during `verdi setup` that we did not find a `.aiida` in `AIIDA_PATH`.

**Comment by greschd** [comment]
Yeah, I agree that would make it simpler for the regular users.

@giovannipizzi @sphuber What's your opinion here? Should we ditch the upwards-search on the path, or keep it with some magic prefix? Or just document it, for backwards-compatibility's sake?
