### ISSUE TITLE
verdi user list "color option"

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2408]
verdi user list has a "--color" option

 * on my terminal, the behavior is the reverse of the expected one: the one user I currently have is colored red in output, if I do *not* specify the --color option (and it *isn't* colored when I specify it)
 * do we need this option? how are the users colored?

**Comment by astamminger** [comment]
@ltalirz doesn't happen for me. When I do `verdi user list` I get the following output
```
(aiida_develop_py36) andreas@ZenBook:~> verdi user list
*user_1: Andreas None (None) [NO_PWD]
*user_2: Andreas None (None) [NO_PWD]
*user_3: Andreas None (None) [NO_PWD]
```
Hower using the `--color` option I get the following
```
(aiida_develop_py36) andreas@ZenBook:~> verdi user list --color
*user_1
*user_2
*user_3
```
with `user_[123]` indeed colored (in something like light purple) but all the additional information is not displayed anymore. I can't imagine this is the expected behavior? However, even if it would output the complete user info (like `verdi user list`does) I do not really see the point in having this output colorized.
