### ISSUE TITLE
Import of Log entries should be checked for existence based on their UUID

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#2448]
We have to see what happens when a node is re-imported with more log entries - We should import the new log entries based on their UUID.

This is a continuation of the work done for issue #2423 under PR #2447

At least a test should be added that demonstrated that if the same node is imported with more log entries, only the non existing log entries should be added to the new DB.

**Comment by szoupanos** [comment]
@giovannipizzi @sphuber 
Could we sync a bit on this? Did we reach a conclusion?

My initial understanding is that we needed to verify that when an export file is re-imported, logs records should not be duplicated. The case of second export file with more log records (where we should add to the destination database the delta of logs) is not considered as a possible option by @sphuber (since a node should be shielded to be exported and no more log records can be added) but I am not sure that we excluded such a scenario - that's the reason why this ticket was generated.

Should we proceed with this implementation? Should we just check the basic case (that when we export the same export file, the log records are not imported twice)?

**Comment by sphuber** [comment]
I think we first need to decide for sure what the role and therefore of `Logs` should be. Originally, these were messages that were attached by the engine to process nodes, while they were being run. In that view, it should be impossible to add new logs to a sealed node, because a sealed node is no longer active by definition.

However, I know of people, for example Leonid, who also use the log system to add messages to nodes after they have been sealed. For example, in his node deletion script, a log message was attached when an output or input was deleted from a node, if I am not mistaken. Obviously in this case, the node is already sealed, so in the first concept I wrote, this would not be possible.

*If* we decide that logs can only be attached to nodes while they are unsealed, then the following logic becomes more easy, because only sealed nodes can be exported. This would mean that by definition, if you export a node with all its logs, one can never later create another export archive with more logs for that particular node. This would mean on the import side, that if a node is already present in the database, then we simply *ignore* the logs. Because if the node already exists, it was either created by this database, or it was imported before, in which case it should already have imported the logs.

Of course here we can come up with edge cases where for example someone has exported an archive with AiiDA `v0.12` (i.e. without logs) that were imported by someone else. If some of the nodes in that archive are now re-exported with `v1.0.0b1` including the logs, it would be impossible to import those. Since this is a side-effect of the fact that logs did not used to be exported, I am not sure if we should support this.

**Comment by giovannipizzi** [comment]
In general I agree.
I think that at the moment, since the logic is not clear/fully defined, there are the issues that @sphuber points out, and also we don't have a clear agreement on *deletion* (of nodes, but also of Logs) I suggest to check all logs, put back the "new" ones avoiding duplicates, so that if I import again the same node with 3 existing logs and 2 new ones, the 2 new ones appear and I am left with 5 total logs (and importing again does not change the number of logs).

**Comment by CasperWA** [comment]
> ... I suggest to check all logs, put back the "new" ones avoiding duplicates, so that if I import again the same node with 3 existing logs and 2 new ones, the 2 new ones appear and I am left with 5 total logs (and importing again does not change the number of logs).

I agree. And this is the approach I have been implementing in PR #2486.

**Comment by szoupanos** [comment]
Great, it's good that we are on the same page.
Thanks!

**Comment by sphuber** [comment]
Fixed in PR #2486
