### ISSUE TITLE
What should be the process_type when creating a CalcJobNode by hand?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2474]
Currently, when storing a CalcJobNode by hand, the process_type is empty.
When you submit a CalcJob process (without subclassing), it stores the module path in the process_type (similar for WorkChain etc.).

Questions:
 1. Should the two operations produce the same result (e.g. storing by a user vs. submission) ?
 2. What should be the value of the string stored (empty, ...)?

Note: Current migrations will put an empty process_type for what used to be a JobCalculation (but will not touch the process_type column for existing WorkChains). Keep this in mind for migrations.

Once this is decided, make sure #2400 is not affected.

**Comment by ltalirz** [comment]
Mentioning @giovannipizzi @sphuber for comment

**Comment by giovannipizzi** [comment]
My opinion:
> 1. Should the two operations produce the same result (e.g. storing by a user vs. submission) ?

Yes

> 2. What should be the value of the string stored (empty, ...)?

Probably I would leave them empty.

Also, this fix should be done, I believe, even if in the future we want to avoid that unsubclassed WorkChain or CalcJob are submitted and stored. Otherwise, querying for a CalcJob with subclassing=False will *not* return bare CalcJobNodes stored by the user (since currently the process_type_string built from the class is instead something like `aiida.work....`)

**Comment by sphuber** [comment]
I agree, bare `WorkChain` and `CalcJob` processes should not be submittable (see issue #2493 ). Currently I think you can, but they will fail. However, they will have created a mangled node in the database. We should make them unrunnable. This way there should only be bare `CalcJobNode` that were created and stored manually. They will currently get an empty `process_type` which I think is the correct behavior

**Comment by sphuber** [comment]
Fixed in PR #2564
