### ISSUE TITLE
Implementation of DbLog migration is extremely slow

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2539]
In PR #2507 the migration of the `DbLog` table was adapted to also account for log entries whose corresponding node was deleted. The query that was used to select these is as follows:
```
SELECT COUNT(*) FROM db_dblog
WHERE
       (db_dblog.objname LIKE 'node.%') AND
       (db_dblog.objpk NOT IN (SELECT id FROM db_dbnode))
```
The usage of   `NOT IN` with the entire set of node ids makes this query terribly slow. On theossrv5 on a database with roughly `800,000` nodes and `400,000` entries, the migration was still not finished after 24 hours.

**Comment by sphuber** [comment]
Fixed in PR #2540

**Comment by szoupanos** [comment]
Something similar has to be applied for the aiida/backends/djsite/db/migrations/0024_dblog_update.py Django migration follows the same logic as the queries mentioned above and it is slow too (more than 1 day - and continues - for a database of 7M nodes).

**Comment by sphuber** [comment]
@szoupanos I have now confirmed the slowness for the Django implementation. I will be pushing a fix soon hopefully. The slowness comes because we use Django's ORM to count the logs we need and this creates a very inefficient query. I think I will just do it with raw SQL as I did for SqlAlchemy

**Comment by szoupanos** [comment]
@sphuber 
Hello Seb! Yes, this should be the solution. If I remember well (that I am not so sure), I copied the SQL query produced by the Django backend for the log migration to the corresponding SQLA migration that you had optimized in the past since you notices that it was slow.

So the solution would be the opposite procedure and it would not be difficult to add the optimized SQL query to the right place at the Django migration (at least, I hope).

**Comment by sphuber** [comment]
I am doing that now, will be pushing a PR soon. First want to test it on the test database
