### ISSUE TITLE
Storing a node changes its hash, due to float rounding

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida_core#2631]
```python
from aiida.orm.data.parameter import ParameterData
p = ParameterData(dict={'test': [3.5615599999999996, 4.508439999999999, 0.8715600000000004]})
print(p.get_attrs())
print(p.get_hash())
p.store()
print(p.get_attrs())
print(p.get_hash())
```
```
{'test': [3.5615599999999996, 4.508439999999999, 0.8715600000000004]}
5632c77efbfe1d0690e71321d0674715f76f5fc14d01b28f4f19bb23
{u'test': [3.56156, 4.50844, 0.87156]}
6f9926c50e8447dff7b7f89751d466ece9f392449db37ebdcf1e9838
```

Only tested on v0.12.3, but I assume this will be the same in v1.

Bit of a nuisance when, for example, you're trying to compare/reuse input Structure nodes, 
created *via* ASE/Pymatgen functions.

**Comment by zhubonan** [comment]
One solution could be to define a certain rounding when calculating the hash of floats. I don't even include so many digits when writing out inputs files for the code...

**Comment by zhubonan** [comment]
I think the float rounding problem is caused by the communication between the database - perhaps python and postgres parse/round float strings and differently, which is something we just have to accept.

As for hashing, this function is used to truncate the float by dropping the last four bits, hope to solve the problem.

https://github.com/aiidateam/aiida_core/blob/e1b858d4fc5a3a0f57d516446d4d123763bbb4f6/aiida/common/hashing.py#L353-L362

But does not mimic what happens when the float is converted to string as it is rounded into base 10 number, which may change more bits than the last 4. For example, when the last 4 bits are '1111' and rounding up may change the fifth (and any other) digits from the end. So this truncation is not guaranteed to work.

For example:
```
In [211]: flt = 1.292934884888484388348398483985 
In [212]: Float(flt).get_hash() 
Out[212]: '62de4f1bcaa8f2242768e57789b4dcde06b70314a35b5c98de70019d04cef9b4'
In [213]: Float(flt).store().get_hash() 
Out[213]: 'fc51ecc97b03bb7ffb0a6b0e36e850749aa295d30bf5e489a05f4496dd1efdcd'
```
Which is caused by rounding while storing that changes more than just the last four bits:
```
In [218]: flt_ = float(Float(flt).store())
In [219]: int_flt = np.float64(flt).view(np.int64) 
In [220]: int_flt_ = np.float64(flt_).view(np.int64)
In [221]: '{0:b}'.format(int_flt)
Out[221]: '11111111110100101011111101110001111101011001110100000111001101'
In [222]: '{0:b}'.format(int_flt_)  
Out[222]: '11111111110100101011111101110001111101011001110100000110111010'
```

But, if I do the same for `np.pi` the hash actually comes as the same.

I think a better way to hash the float is to convert it to string and limit the significant digits to say 14 (`'{:.14g}'`).

**Comment by giovannipizzi** [comment]
Please check discussion in #2124 as well

**Comment by giovannipizzi** [comment]
Some additional thought, also triggered by #2782 

- probably the only way to fix this problem is to add some logic into `clean_value` to round (not truncate) with a bit less precision than the machine precision, and accept that floats in AiiDA will have a bit lower precision than machine precision
- this can be achieved by replacing
  ```python
  if isinstance(val, numbers.Real):
      return float(val)
  ```
  with
  ```python
  if isinstance(val, numbers.Real):
      new_val = float("{:.13g}".format(val))
      return new_val
  ```

Then, the *important thing* is to use *the same* number of digits in the hashing.
I'm not sure that this will *always* work, but I have a strong feeling that this might be ok if the precision in the backend is larger than 13 digits.
In particular I've tried with the script mentioned in #2782, with the following values:
```
[0.544449, 0.5444449, 0.54444449, 0.544444449, 0.5444444449, 0.54444444449,
0.544444444449, 0.5444444444449, 0.54444444444449, 0.544444444444449,
1.324322244324434323e30, 1., 0.3, 2., math.pi, math.e, math.sqrt(2.)]
```
and with serialisation with 14 digits, clean_value+hashing with 13, and while this fails (i.e., `before != after`):
```
before = my_hash(val)
roundtrip = deserialize(serialize(val))
after = my_hash(roundtrip)
```
this works:
```
val = clean_value(val)
before = my_hash(val)
roundtrip = deserialize(serialize(val))
after = my_hash(roundtrip)
```
(of course this is not a proof, but at least we know we are improving the situation.

# Big integers and floats

Another problem however surfaced: if you store a large float that could be stored as an integer, e.g. `1.2e4`, the Postgres+JSONB will actually store it as an integer!!

However, the behavior is really hard to predict. Initially I thought that we could reproduce what SQL does by the following logic in `clean_value`:
```python
if isinstance(val, numbers.Real):
    new_val = float("{:.14g}".format(val))
    if new_val.is_integer():
        return int(new_val)
    return new_val
```
However, this is not correct! Even going down to the SQL level, here is the (to me weird) behavior, and I don't think we have control on it:
```
sqla=> UPDATE db_dbnode SET attributes='{"vals": 1.200e2}'::json where db_dbnode.id=1;
UPDATE 1
sqla=> SELECT id, ctime, node_type, (attributes->'vals') as BIGINT from db_dbnode WHERE attributes->'vals' is not null order by ctime limit 1;
 id |             ctime             |    node_type    | bigint 
----+-------------------------------+-----------------+--------
  1 | 2019-07-01 12:04:24.575765+02 | data.dict.Dict. | 120.0
(1 row)

sqla=> UPDATE db_dbnode SET attributes='{"vals": 1.20e2}'::json where db_dbnode.id=1;
UPDATE 1
sqla=> SELECT id, ctime, node_type, (attributes->'vals') as BIGINT from db_dbnode WHERE attributes->'vals' is not null order by ctime limit 1;
 id |             ctime             |    node_type    | bigint 
----+-------------------------------+-----------------+--------
  1 | 2019-07-01 12:04:24.575765+02 | data.dict.Dict. | 120
```

So: things like `120.0`, `1.2000e2`, ... are considered floats, while things like `120`, `1.2e2`, where we don't specify enough digits after the comma are considered as integers. 

Changing the type as mentioned here above will probably convert uniformly everything to an integer, but I'm not 100% sure it's a good idea (both because it's unexpected to users - even if I would say also the current behavior with 1.2e2 and 120.0 returning different types is unexpected to python users - and because we might have problems with very large float numbers that might give an overflow if written as integers (but I just checked and this does not fail: `int(1.e300)` returns `1000000000000000052504760255204420248704468581108159154915854115511802457988908195786371375080447864043704443832883878176942523235360430575644792184786706982848387200926575803737830233794788090059368953234970799945081119038967640880074652742780142494579258788820056842838115669472196386865459400540160L`

**Comment by giovannipizzi** [comment]
BTW, note that in the `develop` branch as of today (commit acfddd34a7ee02ebbf74ee415cbcde20b1d7e786) the original problem is not visible anymore (this might be due to the switching to Django JSONB that should have a higher precision for floats than before)
