### ISSUE TITLE
Warn users when they are creating new `Data` in a `WorkChain`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2675]
Although this is (or will be) well documented, I predict that many novice users will try creating new `Data` inside Workflows - it's simply something very natural to do: you run some calculations,  you combine some of their outputs and return them in a new `Dict`.

I'm not saying we should allow this (although at some point one could perhaps think of a mechanism to automatically wrap this in a `@calcfunction`), but I think it is very important that we **warn** users that they are doing something wrong.
Otherwise, we end up with a situation like here in the lsmo, where users have run their `WorkChains` and, at the end when they want to export them, they look at the graph and notice that links are missing etc.

@sphuber Is there a way for us to detect that `Data` is created from within a Workflow?
If we can detect this, I would actually even be in favor of (by default) throwing an exception rather than printing just a warning, since it really is something we don't want people to do.

**Comment by sphuber** [comment]
It is a difficult one: this is part of the reason why I set out my crusade on redefining the provenance. Sometimes, it *is* ok to create a new node in a work chain, for example when you pass it to another calculation. Now it won't get an explicit create link from the work chain, but it will have an input link to the calculation node. It is as if you would have created it in the shell beforehand and it was passed to the calculation. Now, your example is of course worse where an actual output is created in the workchain, based on some other outputs. The output will have a return link, but it won't have a direct connection to the outputs that essentially formed the basis for it.

The problem is that I think we cannot distinguish between these two examples, as far as the engine is concerned. There is no way to now if a new node is created in its body whether this is done "correctly" and "conscientiously" or by mistake. Unless I am mistaken, it is either *always* possible to create nodes in a work chain, or it is *never* is. While I see that the latter is maybe better in the example you gave, ultimately I am afraid it is too restrictive in many cases where it really is not that important.

In any case, I am working on the documentation to make this property of AiiDA very clear.

**Comment by ltalirz** [comment]
> Sometimes, it is ok to create a new node in a work chain, for example when you pass it to another calculation. 

I wasn't aware that this is considered "ok". From a provenance point of view I think it is still not ideal since the node comes from nowhere, while its contents might actually be based on the outputs of previous steps in the WorkChain. 
Can you show a few use cases of this for me to understand the common usage patterns better?

Finally, even if we want to allow this, I think it we should still print at least a warning.
People can ignore it but then it's at their own risk.

**Comment by sphuber** [comment]
Consider a simple work chain that just passes some inputs to a calculation. Either a user can create the inputs first and pass them to the work chain, or one of the inputs is created *in* the work chain and then passed. The only difference is that that one node won't have an input link to the work chain. In both cases, the content of the node was *magicked* into existence. Now very often, you will find you want to do something that is very close. For example, you pass an input dict, and often some steps, change just one key and just pass it to the next calculation. Now if we were to forbid this, you would *have* to go through a calculation. Technically this would be the "correct" thing to do, but in practice this can feel like overkill. I am not sure if we should really restrict this option.

A warning may be an option, but again I am not sure if we can easily distinguish the various cases, some of which are more severe than others. Plus it will then maybe be difficult to turn them off and you definitely would want a way to turn them off.

**Comment by ltalirz** [comment]
> Now if we were to forbid this, you would have to go through a calculation.

Good that we are discussing this - I was under the impression that this is exactly what one should do: namely to go through a `@calcfunction` (what used to be called `@workfunction`).
I always understood the mantra that "calculations can `CREATE` data, while workflows can only `RETURN` data" to mean that workflows cannot create Data nodes (with the "cannot" actually being a "should not" because of implementation details).

I fail to see the fundamental difference between:
 * creating a new `Data` node inside a workflow from some information hardcoded in the workflow (which you consider "ok", if I understand correctly)
 * creating a new `Data` node inside a workflow, potentially from the output of previous calculations, and passing it as an input to to a new calculation (here I'm not sure where you would stand ;) )
 * creating a new `Data` node inside a workflow from the output of previous calculations and returning it (which is "not ok")

In all three cases, the information about how this Data node came to be hides in the implementation of the workflow, and the workflow is no longer just a logical framework for organizing how calculations should run.

perhaps @giovannipizzi might want to comment on this as well

**Comment by giovannipizzi** [comment]
That's an important discussion and I think is the only "open point" on my side still on the new provenance model. Maybe we should have a brainstorming meeting on this and the various options, and report back here the final ideas? An option that comes to my mind now (but maybe not good?) is that, if a workfunction starts storing nodes, that we automatically create a corresponding calcfunction that actually creates them, make the CREATE links out of it, add a CALL link from the wf to the cf, and then have the results returned by the wf? Pros: provenance always kept even if the user forgot, Cons: a lot of "magic" and I don't know if there are corner cases where this is not a good idea (also, 1) do we want to use a normal calcfuction, or a specially-tagged calcfunction/a special subclass/other class? and 2) it might look weird - but maybe it's the right thing to do? - to have a calcfunction automatically created when running a work function, but only if nodes happen to be stored).

**Comment by sphuber** [comment]
@giovannipizzi remember our discussion recently when you felt that the real reason for the new split between workflows and calculations is to be able to hide or focus on either data provenance or logical provenance in an easy way? I said that this was a useful consequence but not the original reasoning. For me, this discussion we are having here now, was the very reason I started with the proposal for the redesign. I will try to explain what my thoughts were and why I came to the current design, that consciously includes the *flaw* that Leopold describes. Imagine the alternative where we forbid it, you would need to deal with the following:

1. I am not sure it is so easy to detect if new nodes are being illegally created. You can only check if they are stored or not, which with the new model, a user should rarely ever have to call store. For example, they just pass unstored nodes to a launcher when running a top level process, which should and will be allowed. So the difference is maybe when the unstored node is passed to a process that is being *called* by another. We might be able to code this up, but might not be trivial. However, this still has the downside, that *all* nodes that will eventually be passed in a nested chain, will have to be passed in at the top level, as it is not allowed to create any of them. Not necessarily a problem, but imagine some simple calculation function deep down the line needs a simple `Bool`, this will now have to be propagated all the way up. But let's assume it would be possible to implement this.

2. This implementation would be extremely restrictive and in practice force people to do annoying stuff.
Imagine the following dummy work chain that launches a calculation job, inspecting the results and changing parameters when it fails, to relaunch it with slightly adapted parameters.
```
class SomeWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
    super(SomeCalcJob, cls).define(spec)
    spec.input(parameters, valid_type=Dict)
    spec.outline(
        while_(cls.not_converged)(
            spec.init,
            spec.launch,
            spec.inspect
        )
    )

    def init(self):
        self.ctx.parameters = self.inputs.parameters

    def launch(self):
        return ToContext(calculation=self.submit(SomeCalcJob, self.ctx.parameters))

    def inspect(self):
        if not self.ctx.calculation.is_finished_ok:
            if self.ctx.calculation.exit_status == 400:
                # Change a single parameter 'diagonalization' to 'cg' in the original parametres and relaunch
                self.ctx.parameters = ?
``` 
How would you create the new parameters `Dict` node. With the proposed limitation, you cannot just unpack the original one, change one value of a certain key and recreate a node, you would have to go through a calculation function. Which means you *also* have to pass the "value" and the "key" to be changed, which *have* to be nodes, but you cannot just create them there, but you couldn't have passed them in at the top work chain level neither, not knowing in advance what keys should be changed with what values. The only solution is to make a single calculation function that is designed explicitly for that single case and that can only set this particular to this exact value for a parameter dict, for example `def change_diagonalization_to_cg(parameters)`. Now imagine you would have to create such a function for any possible combination of keys and values for something like Quantum ESPRESSO, or any other code. To me this seems intractable and will make the workflow engine unusable.

3. This is where I came to my conclusion: for any reasonable and usable system, I think it is unavoidable to have the possibility of provenance to be broken. Even if you were able to fix this particular problem; what about leaking in information into calculation functions? Maybe even through something as seemingly innocent as module imports. That is also still possible and just as damaging. That's why I think the only or best solution is to create such a system, where it is *as easy and simple* to explain *and* understand as to *how* and *when* provenance will be broken in AiiDA. This for me was the whole reason to design the provenance as it currently is, because now we can say, workflows *cannot create*, as an absolute. The hope was that  as a result, users would be very careful when still 'creating' data in a workflow, while still giving them the possibility to if they deem the loss of provenance is minimal and acceptable.

P.S. mind you that with versioning of the work chain and storing it (which we are attacking now as a problem) will still have some indirect reference of how and why the data was created within its body.

**Comment by ltalirz** [comment]
@sphuber I definitely get your point and the last thing I want is to make workchains hard to use.

To be honest, I've never really understood why this separation into "logical provenance" and "data provenance" is necessary, and to me that the above discussion shows that it is not really enforceable in practice.
Yes - workchains *do* provide a logical grouping of calculations and this absolutely is a necessary feature. But workchains could simply be considered a "calculation with an outline". No need to restrict what they can create or return.

Perhaps some of the confusion came from the fact that `RETURN`ing data was associated with workflows only. I still get that it is useful to explicitly state that an operation is returning one of the inputs unchanged - but why shouldn't a calculation be able to do that as well?

I'll think a little bit and perhaps get back with an "aiida enhancement proposal" if I find the time.

**Comment by sphuber** [comment]
Fair enough, but the thing you will lose with that proposal and concept is the DAG. However, that is the one fundamental concept that we, I think, all agreed on was useful and didn't want to lose. Of course you could come up with a halfway scheme where work flows can still both create and return, but you won't solve your problem. Even if you allow this, how is the engine to now from which inputs you create a node in an outline step. You would have to do dynamic code inspection and that would be just the beginning. I dare say it is impossible

**Comment by sphuber** [comment]
Proposed solution is to, just like for `workfunctions`, detect unstored nodes being passed to `self.out` of the workchain. This means that the node was created inside the outline step which is illegal and will raise.
