### ISSUE TITLE
Clean the logic in `verdi quicksetup` implementation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2763]
The logic in `aiida.cmdline.commands.setup.quicksetup` tries through a bunch of prompts to fill in the blanks before passing all information to `verdi setup`. The code, however, is still a bit messy and does not use our `InteractiveOption` for the prompting for example, leading to different styles of prompts.

**Comment by ltalirz** [comment]
Just to list a few other changes that were made in #2740 : 
 * `verdi setup` profile name argument became an option
 * `verdi quicksetup` profile name argument became an option

We should briefly discuss whether we want these changes and what the desired behavior of `verdi setup` and `verdi quicksetup` is. I list my suggestions below:

### `verdi quicksetup`

1.1 Running `verdi quicksetup` interactively:
 * general idea: prompt as little as possible
 * I believe it nevertheless makes sense to always prompt for the profile name. Otherwise many aiida users never get introduced to the concept of profiles. This would speak for @sphuber 's change where the profile name becomes an option (note: I believe this used to be the case in earlier aiida versions as well)
 * We need to prompt for the user info. Pre-filling it helps a lot but we can't entirely hide it in this case (otherwise, you risk creating all your data with inappropriate user information).
 * if you provide the name of an *existing* profile, I suggest quicksetup should fail immediately.
   Don't use quicksetup to re-configure an existing profile.

1.2. Running `verdi quicksetup` non-interactively:
 * it would make sense to be able to specify the options that are available in verdi setup, since quicksetup also creates the database for you.
 * if you provide the name of an *existing* profile, it should fail.

### `verdi setup`

2.1. Running `verdi setup` interactively:
 * general idea: prompt for everything but provide sensible defaults
 * we could introduce a `--force` option that allows verdi setup to reconfigure an *existing* profile, (a use case mentioned by @sphuber ). If the `--force` option is not provided, `verdi setup` should fail immediately.

2.2. Running `verdi setup` non-interactively:
 * Requiring the `--force` option makes it safe enough to allow re-configuring non-interactively as well. We would need to check whether the `contextual_default` does the right thing in this case, though

mentioning @giovannipizzi for comment

**Comment by ltalirz** [comment]
Summarizing the discussion with @sphuber and @giovannipizzi: 

 * We change the profile name to being an *option*, not an argument. 
   Note: This was already the case for `quicksetup` in 0.12.x (but not for `setup`).
 * `verdi quicksetup` and `verdi setup` should have the same option names 
 * (some of) the quicksetup options will work differently, in that they will not prompt in interactive mode
 * If a profile name is given that matches an existing profile, both `verdi quicksetup` and `verdi setup`  will prompt for a different name in interactive mode (in non-interactive mode, they will simply fail)

Future:
 * we will provide a separate `verdi profile edit` command (exact name to be decided) that will allow editing of existing profiles (it will almost be an exact copy of the `verdi setup` command).

**Comment by sphuber** [comment]
Just an additional node for `verdi profile edit` that it will only be exactly like `verdi setup` in terms of options, its functionality will *only* serve however to adapt the profile settings. It should not migrate the database (`verdi database migrate`) nor (re)configure users (`verdi configure user`).

**Comment by ltalirz** [comment]
I hope the change of behavior of `verdi setup` is not too much of a problem.
aiida-core is using it in the CI tests, but plugin developers should be using the plugin fixtures, so hopefully they won't be impacted.

**Comment by ltalirz** [comment]
> Just an additional node for verdi profile edit that it will only be exactly like verdi setup in terms of options, its functionality will only serve however to adapt the profile settings. It should not migrate the database (verdi database migrate) nor (re)configure users (verdi configure user).

Exactly, thanks for making this clear.
