### ISSUE TITLE
dependency cleanup

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2800]
Following the discovery of the superfluous `chainmap` dependency, I've made a list of all AiiDA dependencies that are used in less than 2 files in the current `develop` codebase.

I understand that some versions may be pinned for a reason - if this is the case, please let me know. I've used `pipdeptree` to figure out whether packages are *only* dependencies of aiida-core ("top-level dependency") or *also* dependencies of other dependencies (which may result in a different version being installed when removing the version pinning).

Vote to remove:
 - [x] python-mimeparse (mimeparse): never used, top-level dependency
 - [x] anyjson: never used, top-level dependency
 - [ ] ~~psutil: never used directly, also dependency of `circus` (any version). perhaps this pinning should remain?~~ starts to be used in #2795 
 - [x] meld3 (pymeld): never used, top-level dependency
 - [ ] ujson (ultrajson): used in [`aiida/backends/sqlalchemy/utils.py`](https://github.com/aiidateam/aiida_core/blob/8b6169c9ff60a9ed120969b53a687f5925a1e51d/aiida/backends/sqlalchemy/utils.py#L13-L15) but with a try/except, top-level dependency
- [x] click-plugins (click_plugins): apparently never used (?). It seems to me this is actually not needed (would need to check), top-level dependency
- [x] ecdsa: never used, top-level dependency
- [ ] ~~pika: used in `aiida/engine/processes/process.py`, however: (1) it's just using a pika exception; perhaps this can be replaced. (2) pika is a dependency of `kiwipy[rmq]`. Shouldn't we let kiwipy decide the version to install?~~ We keep it for the moment (to be removed once pika is no longer used directly)

Fine to stay - suggestions welcome if functionality can be replaced by existing dependencies:
 - [ ] tzlocal: used in `aiida/common/timezone.py`
 - [ ] passlib: used in `aiida/common/hashing.py`
 - [ ] click-completion: used in `aiida/cmdline/commands/__init__.py`, `aiida/cmdline/commands/cmd_completioncommand.py`
 - [ ] click-spinner (click_spinner): used in `aiida/cmdline/commands/cmd_daemon.py`, `aiida/cmdline/utils/decorators.py`
- [ ] ete3: used in `aiida/cmdline/commands/cmd_node.py`, `aiida/cmdline/utils/ascii_vis.py`.  
- [ ] pyblake2: used in `aiida/common/hashing.py`
- [ ] simplejson: used in `aiida/common/json.py`

@giovannipizzi @sphuber please let me know your opinion and I will prepare the PR

**Comment by sphuber** [comment]
I'm fine with removing all those that you proposed that are apparently not used. Although, are we sure `ecdsa` is not maybe used for some of the `ssh` additional options, like` kerberos`? About `pika`, I added it because we had some trouble in the past. We had `1.0.0b1` dependency, which was also direct dependency of `kiwipy`. Then we updated it for `kiwipy` to `1.0.0`. But now, if you updated it, `pip` would not install the new version because it recognized the dependency as satisified. So for now we decided to be explicit, especially given that we used it directly, albeit it only the exception.

I would certainly keep `click-completion` as it provides auto-completion of parameter values. And since a big part of `aiida-core` is `click` based, I think it is fine to keep the `click-spinner` as well. All the others I would keep as well because they are currently used.

**Comment by giovannipizzi** [comment]
In general I'm ok to remove unused dependencies (but I agree with @sphuber in keeping the used ones, unless it's easy to replace them; maybe if they are "compulsory", they could be made optional, e.g. is `simplejson` essential or only gives a performance benefit?)

For the ones that appear unused:
- `ujson` is also used in the rest API - most probably it can be simply removed with standard JSON? or merged with `simplejson` if the idea is to give better performance?
- things like `mimeparse`, `ecdsa`, ... - we should check as @sphuber says if they are needed to improve functionality of some of the dependencies, otherwise ok to remove (or e.g. for `ecdsa` to move in the ssh/kerberos optional dependencies?). It would be also useful to see if looking at the `git blame` we understand who added them, maybe the commit message will help understanding if they are needed
- psutil: will be actually needed by #2795 so maybe we can just keep it

**Comment by ltalirz** [comment]
Thanks to both for your feedback!

> are we sure ecdsa is not maybe used for some of the ssh additional options, like kerberos

I did some digging:
 * ecdsa: introduced by @cepellotti in c254d04616d5131ede852568cdb609f488d4e4e1 . It's never mentioned explicitly what it's for - perhaps just for some experiments? anyhow, the documentation of that time states that paramiko doesn't support ecdsa keys and one should replace them (but that's no longer the case)
```
+  * If the above point is not sufficient, check the format of the remote host
+    key. On some machines (we know that this issue happens at least on recent
+    Ubuntu distributions) the default format is not RSA but ECDSA. However,
+    ``paramiko`` is still not able to read keys written in this format.
+
+    To discover the format, run the following command::
+
+      ssh-keygen -F FULLHOSTNAME
+
+    that will print the remote host key. If the output contains the string
+    ``ecdsa-sha2-nistp256``, then ``paramiko`` will not be able to use this
+    key (see below for a solution).
+    If instead ``ssh-rsa``, the key should be OK and
+    paramiko will be able to use it.
+
+    In case your key is in *ecdsa* format, you have to first delete the key
+    by using the command::
+
+      ssh-keygen -R FULLHOSTNAME
+
```
 * mimeparse and meld3: introduced by @cepellotti in 4c7b0dc25a2f967cc72f10fec5b288bcb1fd9269 which reads "Freezing the exact dependencies that I am using for the current installation of django". I guess it was a dependency of django at some point.


> About pika, I added it because we had some trouble in the past. We had 1.0.0b1 dependency, which was also direct dependency of kiwipy. Then we updated it for kiwipy to 1.0.0. But now, if you updated it, pip would not install the new version because it recognized the dependency as satisified. So for now we decided to be explicit, especially given that we used it directly, albeit it only the exception.

I see. I would still argue that it is kiwipy's job to specify which version of pika it is happy with, not aiida-core's. Also, the current way of doing things can lead to dependency conflicts when we forget to update the pika version in aiida-core.
Still, as long as we use pika directly in aiida-core I guess one can make a case for it.

> ujson is also used in the rest API - most probably it can be simply removed with standard JSON? or merged with simplejson if the idea is to give better performance?

Thanks for noticing - I got confused with us having both `import ujson` and `import ultrajson` in the code base.
The line you are referring to was introduced by Fernando, and it's only in the `BandsDataTranslator`. I think it is safe to replace with `aiida.common.json`.

I think I know enough to prepare the PR.
