### ISSUE TITLE
Default value of the exit status

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#2999]
The default value of the exit status is not being present. Sometimes we want to return the exit status at the end of a method and then before doing that we first need to check if it is present.

Is there a reason why the default `exit_status` is not `0`?

**Comment by sphuber** [comment]
Can you be a little more specific? The default value of `exit_status` **is** zero, as long as the process state is `Finished`. What case are you encountering where this is not the case?

**Comment by espenfl** [comment]
Actually when thinking about this, this is not due to the `exit_status`, but just a common attribute used for temporary storing an exit code. Say that one is doing some analysis and ejects one exit code, then we change it, then finally we want to return. For the workchains I just dumped this is `self.ctx.exit_status` and returned whatever value was there on method end. But it would be tempting just to write directly to `self.exit_status`. When doing that, for instance on `Parser` yields an `AttributeError` unless we have set an exit code somewhere. So in order to avoid a test before return, this should be initialized to zero. That could be `exit_status` or something else. If course we could just issue it to zero for the local parser, calc or workchain, which is kind of what we are doing now. Minor thing though.

**Comment by espenfl** [comment]
Let us leave it like it is for now an reopen if this is something other users also wants.

**Comment by sphuber** [comment]
I will put my objections here as discussed elsewhere, for reference.

I think this will be a common workflow yes, I do it myself too, but I don't think this should become automatic, because it might suprise people. They might set the process instance attribute `exit_status` with a different reason in mind and now this gets special meaning. And that is all just so you do not have to have a single line yourself in the logic `if self.exit_status` to see if you need to return it or not. That's why I do not think it is a good idea to hard-bake this into the process classes.
