### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by obgeneralao** [aiidateam/aiida_core#362]
Hi,
I got the script from  "examples/submission/test_pw.py" submitted successfully ,  however  I got the error in my aiida.out

_Local host:        hpc-A1
	  Application name:  /opt/hpc/soft/beta/plain_pw/espresso-5.4.0/bin
	  Error:             Permission denied_

Is aiida trying to copy something from /opt/hpc/soft/beta/plain_pw/espresso-5.4.0/bin? 

And the debug log file is

02/10/2017 08:03:08 PM, aiida.execmanager: [DEBUG] [retrieval of calc 38] Storing retrieved_files=None
02/10/2017 08:03:10 PM, aiida.execmanager: [ERROR] [parsing of calc 38] The parser returned an error, but it should have created an output node with some partial results and warnings. Check there for more information on the problem

**Comment by giovannipizzi** [comment]
Hi,
just as a  comment, tickets are not intended for support. Please write to the mailing list for this (information on aiida.net).

In your case, no, AiiDA should not try to copy anything from there. Go in the folder 'verdi calculation gotocomputer PK', try to run by hand again the submission script (qsub _aiidasubmit.sh or equivalent command) and check what the problem is.
