### ISSUE TITLE
Import Querybuilder at verdi shell start

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#416]
So far QueryBuilder is not among the classes imported when the verdi shell is started. But it would be very practical not to have to import it everytime. It is as common as other already imported classes.

**Comment by nmounet** [comment]
I agree.

**Comment by lekah** [comment]
As the majority feels like. I left it out to keep the imports in the beginning lighter. Maybe we can time the way @giovannipizzi  did for #376  and see if the time added by an import is negligible.

**Comment by szoupanos** [comment]
I also agree with the automatic import if it doesn't affect the loading time.
Maybe it makes sense to be imported by default in 'verdi shell' and not in 'verdi run'.
(Since verdi shell is opened by users a few times and kept open for a while - so loading may not matter too much / On the other hand verdi run is used to run scripts - so loading matters more)

I am not sure though if there should be a difference on the default (AiiDA related) imports of these 2 commands (to avoid user confusion).

**Comment by giovannipizzi** [comment]
Times in my computer goes (for 'verdi run' on an empty file) from ~640ms to ~720ms. I believe this is still ok, as importing the QueryBuilder is essential. I created a branch, if there are no strong opponents I will include this in the branch for 0.9.0.

**Comment by giovannipizzi** [comment]
Also, maybe this time can be reduced by moving some module-wide imports to inside the methods? Probably there's only one or two that are slow (to check, though)

**Comment by waychal** [comment]
Imported QB as default module for verdi commands. To make verdi faster following changes are made:
- added reentry in setup.py
- moved numpy import statement in function in common/hashing.py

Note: Django registry takes most of the time and makes verdi command slower.

**Comment by giovannipizzi** [comment]
Fixed in #576
