### ISSUE TITLE
Extraneous suggested value for scheduler type

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#550]
When setting up a new computer via `verdi computer setup`, an extraneous value `pbsbaseclasses.PbsBaseClass` appears among the suggested valid scheduler types.

**Comment by szoupanos** [comment]
The "problem" here is the automatic discovery of new plugins.
aiida.common.old_pluginloader._find_module searches modules that are a subclass of aiida.scheduler.Scheduler and <class 'aiida.scheduler.plugins.pbsbaseclasses.PbsBaseClass'> satisfies this condition.

Let's discuss how the plugins were loaded in the past and how this problem was avoided.
A fast and dirty solution is to have a flag on the plugins that should not be loaded (like the PbsBaseClass)  - because they are base classes of plugins that should be extended and do not make sense independently - .

Let me know your opinion.

**Comment by giovannipizzi** [comment]
I agree that we should/can flag it as 'abstract' and have the metaclass remove automatically the flag when subclassing. However we need also to add the check in the plugin loader.
I'm wondering if we shouldn't postpone this issue to the next release, because maybe the problem gets solved when fully migrating to the new plugin system, without the need to add hacks.
