### ISSUE TITLE
Context does not have 'iteritems' attribute

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#630]
``workchain.Context`` does not have an ``iteritems`` attribute. This contradicts the documentation: http://aiida-core.readthedocs.io/en/latest/work/index.html#workchains (last example).

There are some possible solutions to this:
* Just fix the documentation. However, ``iteritems`` is a useful feature
* In ``Context.__getattr__``, dispatch to ``getattr(self._content, key)`` **after** ``self._content[key]``
* In ``Context.__getattr__``, dispatch **only** to ``getattr(self._content, key)``

The second option has the advantage of keeping backwards compatibility (and being a bit easier to type in the common case), while the third is cleaner (no mix between ``__getattr__`` and ``__getitem__``). One might imagine that something like ``items`` could also be a key in the ``_content`` dict, in which case the ``.items`` access is ambiguous -- the user probably won't know which one will be returned.

**Comment by greschd** [comment]
Another option: promote ``_content`` to a public attribute, and document the explicit use (``ctx.content.iteritems()`` instead of ``ctx.iteritems()``).

**Comment by sphuber** [comment]
In the current `develop` which is `v1.0.0b1`, the context is now an instance of `aiida.common.extenddedicts.AttributeDict` which is a direct sub class of `dic`. As a result the context should now have the `iteritems` attribute. The link you gave to the docs is now dead so I am not sure what the original situation was, but I think it is safe to say that this problem is no longer applicable. Please reopen if this is not the case
