### ISSUE TITLE
WorkChain step which takes a long time is executed multiple times

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#658]
Measurements from a simple WorkChain with two steps, each submitting one calculation. Timeout in the first step.

Timout (s) | \# instances first step | \# instances second step
--|--|--
20 | 5 | 1
40 | 8 | 1
60 | 8 | 2

* Only ``submit`` is affected, not ``run``.
* Going back to ``0c407604b8f255946`` does not fix the issue.
* The step itself is executed multiple times (writes the ``report`` messages etc.), not just the calculation it spawns.

**Comment by broeder-j** [comment]
Same here. In general submit and async are to use with care.
I'm not sure if this issue stays with 2 instances per step. 
To point out how critical this is: In Juni I ran a workflow which should produce around 1000 nodes, but because subworkchains were submitted several times, which themselves executed things several times, it ended up with 8000 nodes instead. I got a result through, but used 4+times the computational resources. It seems to happened only to steps which contain submit/async. I circumvented this issue by launching all workchains/calculations from lists, which are emptied after the calculations/workchains are submitted, therefore if it runs through the step a second time nothing happens.

**Comment by broeder-j** [comment]
I did not understand the issue back then. I thought it had something to do what the daemon does, or how busy the database is (there were also other issues at that time) and the circumvent of this was by accident.

**Comment by sphuber** [comment]
I have been working on this problem for the past few days and it seems like I have been able to fix it. The fix is currently open for review in PR #663 . Dominik and me have tested our previously failing example and it seems to have done the trick

**Comment by broeder-j** [comment]
Thanks a lot you two!
