### ISSUE TITLE
Django implementation of export does not use QueryBuilder

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#686]
The Django implementation of the export functionality does not go through the `QueryBuilder` to determine the ancestral nodes that need to be exported, but rather go directly through the Django ORM. Link types are not considered in these queries and so with the arrival of RETURN links, infinite recursions may ensue. The entire Django backend should go through the `QueryBuilder` for all its queries.

**Comment by szoupanos** [comment]
It seems possible from a first look to use export_sqla as a general function of export in AiiDA (for both backends).

There are 2 problems to be addressed:
1) QueryBuilder doesn't handle NULL/None values for _metadata & transport_params fields of Computer (line 509 of querybuilder_django.py)
2) For some reason at aiida.backends.tests.export_and_import.TestSimple#test_6 we end up decoding a JSON of the kind {u'workdir': u'/tmp/aiida'} and the decoder fails because it expects double quotes for the property name.

The (1) is a QueryBuilder problem and it will be addressed. Regarding the (2), I would like to have a look (first of all) at why we arrive with such a JSON for decoding.

By fixing (1) all tests, except test6, of import/export under Django pass when using export_sqla as export method.

**Comment by szoupanos** [comment]
This should be OK.
