### ISSUE TITLE
Migration script need to be written to fill in absent link types

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#687]
Due to, among other things, broken export/import functionality, which did not write nor read link types, current databases may contain links without link types. In preparation of a true migration to the future new link system, a migration script needs to be written to bring existing databases to an internally consistent state with the current link system. That means that for links without a type the correct link type should be inferred. We have the following potential node combinations, with the link type that should be inferred by the migration. Note `Calc` nodes are `JobCalculation` and `InlineCalculation`, whereas `Work` nodes are `WorkChain` and `WorkFunction` nodes.

- `Data` -> `Calculation`: `INPUT`
- `Calculation` -> `Data`: `CREATE`
- `Work` -> `Data`: `RETURN`
- `Data` -> `Work`: `INPUT`
- `Work` -> `Calculation`: `CALL`
- `Code` -> `Calculation`: `INPUT`

Note that we will never create a `CREATE` link between a `Work` and a `Data` node. Since this was allowed in the current system, this migration may destroy some provenance, as `Data` nodes that were created by a `Work` nodes, will lose their explicit creator. However, since in the future link system, `CREATE` links by `Work` nodes will be not allowed anyway, this is already a step in the direction we are unavoidably headed anyway.

**Comment by szoupanos** [comment]
We should also think how can efficiently test (if we can) that the link migration was executed correctly (and that its logic was correct - we did not miss any corner cases etc).

**Comment by szoupanos** [comment]
These are interesting links on how we can test Alembic (used for SQLA migrations).
http://alembic-verify.readthedocs.io/en/latest/example_unittest.html#full-example-unittest
http://alembic-verify.readthedocs.io/en/latest/

They focus on how we can check that the final DB schema generated by the migrations is compatible to the models (something good since sometimes we use SQL commands to pass from one version to another).

I believe that something similar can be used for checking that a migration is correct.
E.g. In our case with the link type update, we go to revision n-1, we create a database with some nodes with the link types than need an update, we do the final migration and we do the check if everything is as expected.

These should also be the Django equivalent too...

**Comment by sphuber** [comment]
Merged into `release_v0.10.0` with PR #771
