### ISSUE TITLE
REST API: add endpoint to check if server is up and running

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#793]
Add endpoint in AiiDA REST API to check if server is up and running. It would help to do a test request to the server. If we receives 200 status, it means we can start to make other requests.

**Comment by dev-zero** [comment]
I would probably check for:

- the pidfile
- a process running under the PID found in the PID file (note: it may be possible that the PID file wasn't removed properly due to a restart and the PID was already recycled by the OS, so one would probably also have to check the execname)
- a daemon timestamp

Implementation of this may or may not depend on whether #790 is merged in 0.10.0

**Comment by waychal** [comment]
In this context "server" means a REST API server. It can be started using "python api.py"  in "aiida_core/aiida/restapi/" folder or using Apache. From browser, we can send test request having url something like "http://localhost/testserver" which will return status 200 if it is successful.

It is not related to AiiDA daemon.

**Comment by dev-zero** [comment]
Ok :)

But why then not make it a proper REST resource like http://localhost/server/stats which in the future may be extended to return some server stats?

**Comment by waychal** [comment]
Its good idea. We can add "http://localhost/server/stats" or "http://localhost/server/info" endpoint which will return the server statistics like current AiiDA version it is using and "http://localhost/server/endpoinds" which will return the list of endpoints available on this server.

**Comment by waychal** [comment]
This feature is implemented and also merged.
