### ISSUE TITLE
StructureData stores tags in fragile fashion

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#853]
When an ASE atoms object is converted to a StructureData its tags are apparently stored indirectly in the kind names. Unfortunately, this is somewhat fragile:

```
>>> atoms = build.molecule("H2O")
>>> atoms.center(vacuum=1.0)
>>> atoms.set_masses([16., 1., 2.]) # semi-heavy water
>>> atoms2 = StructureData(ase=atoms).get_ase()
>>> atoms2.get_tags() # should be [0, 0, 0]
[0 0 1]
```

**Comment by giovannipizzi** [comment]
I'm not sure I understand the problem. Maybe however it's not clear to me what the tags are supposed to do. The behaviour you specify is due to the fact that the two H atoms have different masses so when going back to ASE, AiiDA sets the two H atoms with two different tags. 
What is the behaviour you would expect?

**Comment by oschuett** [comment]
Tags in ASE are a simple mechanism for annotating each atoms with an arbitrary integer. By default all atoms have `tag=0`. Hence, in the above example the last line should read `[0, 0, 0]`.

**Comment by giovannipizzi** [comment]
The point is that we use tags as (the only?) way to map different kinds (in AiiDA) to different ase.Atoms.

When you go from ASE to AiiDA, as the two atoms have different masses, two different kinds are created. When going back to ASE, AiiDA tries to ensure that the two atoms are stored as different, in some way, and does this by using tags. 

Indeed, probably this wouldn't be necessary for masses, as the mass is an explicit property of an ASE.Atom, but is necessary e.g. when two atoms are assigned the same physical properties (masses, symbols etc.) but still different kinds (needed e.g. when wanting to assign different starting magnetizations or different pseudo potentials to different atoms, at least in some codes like QE).

I don't know if there is a good solution (that is general also beyond ASE). The issue here is that there is no concept of 'kinds/species' in ASE, AFAIK.

A practical solution, if you need to go back and forth between AiiDA <-> ASE, is to store either the kinds or the tags in some additional variable, and re-apply them at the end, if you know what you want to get. It is what is done, e.g. in `seekpath` in the AiiDA wrappers, when getting different integers for each different kind, to pass to seekpath+spglib, and then to get back the AiiDA structure with the same kinds as in the input.

If you instead have a better solution (general beyond ASE) let us know (and ideally also not too "messy" to code the StructureData is already quite complex now unfortunately)

**Comment by oschuett** [comment]
Thanks for the detailed explanation. Indeed ASE does not have kinds. And others are suffering from it as well: https://wiki.fysik.dtu.dk/ase/development/proposals/labels.html.

> When going back to ASE, AiiDA tries to ensure that the two atoms are stored as different, in some way, and does this by using tags.

So, what's the advantage of this? The AiiDA kinds information is still lost, right?

I would have two proposal:
- **Pragmatic:** Add a tag attribute to the AiiDA kinds and use only this to set the ASE tags.
- **Ugly**: Abuse Python's long integer to store the kind label as a large number in the ASE tags.

**Comment by giovannipizzi** [comment]
Hi, 
the pragmatic solution in in some sense already implemented, you can check in the StructureData class for `_internal_kind_tags` (but I remember that implementing it was a nightmare to get the right logic in all cases).

Having at least different tags for different kinds is still useful even if the info on kinds is lost because (at least if the implementation didn't change and there are no bugs - but there are a few tests for this) if you do the "other" roundtrip, AiiDA->ASE->AiiDA, you go back to AiiDA with different kinds (AiiDA will take care of creating different kind with the same info, and different kind names). No guarantee that they are the original ones, but it should be unless one is not doing something very weird - just the name will be probably different, even if the default logic tries to give back the same name when it's assigned in some simple way - e.g. Ba1 Ba2 for Barium, with consecutive integers etc.

**Comment by oschuett** [comment]
Ok, I guess we should just stop using ASE tags then.
