### ISSUE TITLE
Pre-commit documentation - Package installation under ubuntu

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#859]
I am not sure if the documentation of the pre-commit is complete:
http://aiida-core.readthedocs.io/en/latest/developer_guide/developers.html?highlight=pre-commit

At my Ubuntu VM, I had to manually install the following ubuntu packages to make it work: gem, ruby-dev (and maybe travis).

**Comment by ltalirz** [comment]
the travis stuff is new and it doesn't work with my anaconda python installation.
with just the first two parts (prospector + yaml) it worked for me on MacOSX as described in the documentation.

**Comment by DropD** [comment]
the travis linter is annoying, it would be very helpful but it requires the travis ruby gem. pre-commit will try to install it, however it turns out to be non-trivial (it is a gem with native extensions). It requires a sudoless gem command, gcc and a bunch of libraries.

Maybe we should disable it for now?

**Comment by ltalirz** [comment]
I'd vote to remove it for now.
Up to you.

**Comment by ltalirz** [comment]
I don't think so https://github.com/aiidateam/aiida_core/blob/206be13c409e2a404308d0562acb96a5a3e66e66/.pre-commit-config.yaml#L79-L86

But I haven't had any problems with pre-commit recently, so for me it's fine to close...
