### ISSUE TITLE
Zombie WorkChains

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#893]
We encountered the problem that some WorkChains, which had previously failed, get resurrected on every aiida daemon restart. This seems to be cause by some left over pickle files in
`.aiida/repository/workflows/running`. The problem disappears when the directory is emptied manually.

**Comment by sphuber** [comment]
Which version of `aiida_core` are you running where you encounter this issue?

**Comment by oschuett** [comment]
I'm using aiida-core==0.9.1.

**Comment by sphuber** [comment]
Ah, in that case I probably know what the cause is. We fixed that bug in the current release candidate `v0.10.0rc2` which is already released on pip. You can install it with `pip install aiida-core==0.10.0rc2`. We are planning to release the final version `0.10.0` tomorrow. You can see the reference to this bug fix in the [`CHANGELOG.md`](https://github.com/aiidateam/aiida_core/blob/develop/CHANGELOG.md)

**Comment by oschuett** [comment]
Cool, thanks a lot!
