### ISSUE TITLE
Logging to celery log is broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#943]
In the current `develop` branch, I am no longer seeing any of the report logs coming from running workchains in the daemon log. When a `WorkChain` calls `report`, it fires a message to the attached logger, which triggers the `DbLogHandler` causing it to end up in the database. These messages still show up just fine. However, I also used to see these messages in the normal daemon log. Those are now no longer there. What I do see frequently are errors like the following:

```
[2017-11-21 11:44:06,559: WARNING/Worker-6] Traceback (most recent call last):
[2017-11-21 11:44:06,559: WARNING/Worker-6] File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
[2017-11-21 11:44:06,559: WARNING/Worker-6] stream.write(fs % msg)
[2017-11-21 11:44:06,559: WARNING/Worker-6] IOError: [Errno 32] Broken pipe
[2017-11-21 11:44:06,559: WARNING/Worker-6] Logged from file log.py, line 282
```

I think these occur roughly when the workchains fire a report, so I think the two are related but I am not sure.

**Comment by dev-zero** [comment]
Might be related to my PR which dropped supervisord: we are starting the celery worker with open pipes to stdout/stderr towards the `verdi daemon` which we then abandon (hence the possibility for a `broken pipe`). But we are also passing `--logfile LOGFILE` to `celery`, which tells it to continue logging there instead of `stderr`, and to which I assumed the parent `celery` process to redirect all output from its workers. On the other hand, it is still possible that for some reason the original file descriptor for stdout/stderr still ends up in the forked workers.

The subprocess configuration was taken from the previous code for starting supervisor, but there it most likely didn't matter since supervisor was forking again. Interestingly I tried to run `celery worker` with the `--detach` option which should properly close all the fds, but Celery refused to run in that mode (don't remember the error message though).

Can you post the complete traceback or is that already all? Do you have a MWE?

**Comment by sphuber** [comment]
That is everything I have, there is no real crash, just everytime a `WorkChain` emits a log message, instead of seeing it in the daemon log, I see that error message. It is always the same

**Comment by sphuber** [comment]
I have looked a little bit more into this issue and one example of where the exception is thrown is on line 41 of `aiida/core/dev/aiida/daemon/workflowmanager.py`.
In that file the logger is defined as follows:

```
from aiida.common import aiidalogger
logger = aiidalogger.getChild('workflowmanager')
```

where the `aiidalogger` is just the base logger:

```
aiidalogger = logging.getLogger('aiida')
```

Now for some reason, any logger that seems to derive from the `aiida` logger and also the `aiida` logger itself, will throw the broken pipe exception when used to log in the `execute_steps` function of the `workflowmanager`. However, if I get a new logger, `logger = logging.getLogger('random_name')` it logs to the celery log file just fine. It seems to have to do then with the fact that the preconfigured `aiida` logger, which is configured with `logging.config.dictConfig(LOGGING)` in `aiida/__init__.py` is broken when used by a process in a celery worker.

Unfortunately I know next to nothing about celery and have no clue where to look next. Hopefully this will give you some idea though.
