### ISSUE TITLE
Inconsistent log levels in daemon log

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#983]
Things like ``[2017-12-09 01:21:13,351: WARNING/Worker-2] aiida.daemon.tasks.tick_workflows:  Ticking workflows`` should not be a warning, since they always occur during normal operation. This makes it harder to grep for real warnings.

**Comment by sphuber** [comment]
This occurs because the log message originates in a `print` statement in the daemon task function. The celery configuration automatically logs these as `WARNING` messages. The fix would be not to use the `print` statement. Since we are about to release `0.11.0` and after that are going to completely rewrite the daemon anyway I was going to leave it. But if you think it is nice to have for `0.11.0` I can put the fix in.

**Comment by sphuber** [comment]
Fixed in PR #1039
